"""Persistent conversation memory for the agent.

The LLM sees its full conversation history each heartbeat, giving it
continuity across sessions — it remembers what it said, who it talked
to, and what posts it engaged with. This is the same mechanism that
makes chatbots feel like they "remember": the history is fed back in.
"""

from __future__ import annotations

import json
import logging
import os
from pathlib import Path

log = logging.getLogger("colony-agent")


class AgentMemory:
    """A persistent, rolling conversation history.

    Messages are stored as OpenAI-format dicts: {role, content}.
    The system message is always first and not counted toward limits.
    Old messages are summarized when the history exceeds max_messages.
    """

    def __init__(self, path: str = "agent_memory.json", max_messages: int = 200):
        self.path = Path(path)
        self.max_messages = max_messages
        self._messages: list[dict[str, str]] = []
        self._load()

    def _load(self) -> None:
        if self.path.exists():
            try:
                with open(self.path) as f:
                    saved = json.load(f)
                if isinstance(saved, list):
                    self._messages = saved
            except (json.JSONDecodeError, OSError) as e:
                log.warning("Could not load memory from %s: %s", self.path, e)

    def save(self) -> None:
        """Atomic save to disk."""
        tmp = self.path.with_suffix(".tmp")
        with open(tmp, "w") as f:
            json.dump(self._messages, f, indent=2)
        os.replace(tmp, self.path)

    @property
    def messages(self) -> list[dict[str, str]]:
        """The full message history."""
        return list(self._messages)

    def add(self, role: str, content: str) -> None:
        """Append a message to the conversation."""
        self._messages.append({"role": role, "content": content})

    def get_messages_for_llm(self, system_prompt: str) -> list[dict[str, str]]:
        """Return the message list ready for an LLM call.

        Prepends the system prompt (always fresh, never stored) and
        returns the conversation history.
        """
        return [{"role": "system", "content": system_prompt}, *self._messages]

    def needs_trim(self) -> bool:
        """Whether the history exceeds the configured limit."""
        return len(self._messages) > self.max_messages

    def trim(self, summary: str) -> None:
        """Replace old messages with a summary, keeping recent ones.

        Keeps the most recent half of max_messages and prepends the
        summary as context. The summary should be generated by the LLM.
        """
        keep_count = self.max_messages // 2
        recent = self._messages[-keep_count:]
        self._messages = [
            {"role": "assistant", "content": f"[Memory summary of earlier interactions]\n{summary}"},
            *recent,
        ]
        log.info("Trimmed memory: kept %d recent messages + summary.", keep_count)

    def clear(self) -> None:
        """Reset the conversation history."""
        self._messages = []

    def __len__(self) -> int:
        return len(self._messages)
